# Change these first
owner: 0xb0y # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sinkaroid Frontbase
    url: https://sinkaroid.io
  - name: Chaldea Landing Page
    url: https://chaldea.dev
  - name: Scathach Landing Page
    url: http://scathach.dev
  - name: V3 REST API
    url: https://scathach.redsplit.org/api
  - name: CDN ngocok-static
    url: https://static.hentaicdn.com
  - name: CDN ngocok-dikalasedih
    url: https://cdn.pururin.io
  - name: WebMail
    url: https://scathach.redsplit.org:2096
  - name: Loli Minor Appeals
    url: https://scathach.redsplit.org/static/?params
  - name: Nhentai Graber
    url: http://miyako.redsplit.org
  - name: CabulAPI Reddit
    url: http://192.145.238.5/~pasirm5/v3/cabul/?hentai

status-website:
  cname: status.scathach.dev # Custom CNAME
  logoUrl: https://github.githubassets.com/favicons/favicon.svg
  name: Service Status
  introTitle: "ScathachStats"
  introMessage: Status inidicators for services provided by Scathach
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
