# Change these first
owner: 0xb0y # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sinkaroid Frontbase
    url: https://sinkaroid.io
  - name: Chaldea Landing Page
    url: https://chaldea.dev
  - name: Scathach Landing Page
    url: http://scathach.dev
  - name: V2 REST API
    url: http://192.145.238.5/~pasirm5/v3
  - name: V3 REST API
    url: https://scathach.redsplit.org/api
  - name: CDN ngocok-static
    url: https://cdn-ngocok-static.sinxdr.workers.dev
  - name: CDN ngocok-dikalasedih
    url: https://cdn-ngocok-dikalasedih-static.sinxdr.workers.dev
  - name: WebMail
    url: https://scathach.redsplit.org:2096
  - name: Loli Minor Appeals
    url: https://scathach.redsplit.org/static/?params

status-website:
  baseUrl: /status
  logoUrl: https://github.githubassets.com/favicons/favicon.svg
  name: Service Status
  introTitle: "ScathachStats"
  introMessage: Status inidicators for services provided by Scathach
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
