# Change these first
owner: 0xb0y # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: http://scathach.dev
  - name: Api handled by Skadi
    url: https://skadi.redsplit.org/v3/
  - name: Api handled by Shishou
    url: https://scathach.redsplit.org/api/

status-website:
  cname: status.scathach.dev # Custom CNAME
  logoUrl: https://github.githubassets.com/favicons/favicon.svg
  name: Service Status
  introTitle: "ScathachStats"
  introMessage: Status inidicators majority APIs should covered here.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
